# Generated by Django 5.0.1 on 2024-01-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_category_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
